In [1]:

name = 'NIT'
for i in name:
    print(i)

N
I
T


In [2]:
name1 = [1, 3.4, 2+1j, 'hello']
for i in name1:
    print(i)

1
3.4
(2+1j)
hello


In [3]:

for i in [1,2.3,2+4j,'hello']:
    print(i)

1
2.3
(2+4j)
hello


In [4]:
range(5)

range(0, 5)

In [5]:
for i in range(5):
    print(i)

0
1
2
3
4


In [6]:

for i in range(1,10,2):
    print(i)

1
3
5
7
9


In [7]:
# # print the value which is divisible by 5 table 
for i in range(1,21):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [8]:
for i in range(1,51):
    if i%5==0:
        print(i)

5
10
15
20
25
30
35
40
45
50


In [9]:

for i in range(1,51):
    if i%5!=0:
        print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39
41
42
43
44
46
47
48
49


In [10]:

# LETS DISCUSS ABOUT 3 KEYWORDS -- BREAK || CONTINUE || PASS
# BREAK STATEMNT - if you apply break statment in a loop then it will end the loop
# Pass = skips block of code( function, class etc)
# Continue= skips 1 step/iteration during loop 
# Break= jumps out of the function/loop


In [11]:

for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [12]:
for i in range(1,11):
    if i == 10:
        break
    print(i)

1
2
3
4
5
6
7
8
9


In [13]:
for i in range(1,11):
    if i == 6:
        continue
    print(i)

1
2
3
4
5
7
8
9
10


In [14]:

for i in range(1,11):
    if i == 6:
        continue
    print('Hello :',i)

Hello : 1
Hello : 2
Hello : 3
Hello : 4
Hello : 5
Hello : 7
Hello : 8
Hello : 9
Hello : 10


In [15]:

#PASS Statement - pass the code & it wont go ( code give you the error)

In [17]:
for i in range (1,10):

_IncompleteInputError: incomplete input (1415360069.py, line 1)

In [18]:
for i in range(1,11):
    pass

In [19]:
for i in range (1,11):
    if i%3==0:
        print(i)
print('end')

3
6
9
end


In [20]:

for i in range(1,21):
    if i%3 == 0:
        continue
    print(i)
print('end')

1
2
4
5
7
8
10
11
13
14
16
17
19
20
end


In [21]:
for i in range(1,31):
    if i%3==0 or i%5==0:
        continue
    print(i)

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29


In [22]:
for i in range(1,21):

    if (i%2==0):
        #print('Event')
        continue
    else:
        print(i)
print('Bye')

1
3
5
7
9
11
13
15
17
19
Bye


In [23]:

print('# # # #')
print('# # # #')
print('# # # #')
print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [24]:
for i in range(1,5):
    i=i+1
    print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [25]:
for i in range(1,5):
    if i<=5:
        print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [26]:

for i in range(4):
    print('#')

#
#
#
#


In [27]:
for i in range(4):
    print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [29]:
for j in range(4):
    print('#',end = ' ')
for j in range(4):
    print('#', end = ' ')

# # # # # # # # 

In [30]:

for j in range(4):
    print('#', end = ' ')
    
print()

for j in range(4):
    print('#', end = ' ')
    

# # # # 
# # # # 

In [31]:

for j in range(4):
    print('#', end = ' ')
    
print()

for j in range(4):
    print('#', end = ' ')
    
print()
    
for j in range(4):
    print('#', end = ' ')
    
print()

for j in range(4):
    print('#', end = ' ')

# # # # 
# # # # 
# # # # 
# # # # 

In [32]:

for i in range(4):
    for j in range(4):
        print('#', end =" ")
    print()
    # pease use debug mode in pycharm


# # # # 
# # # # 
# # # # 
# # # # 


In [34]:
for i in range(4):
    for j in range(1+i):
        print('#', end = ' ')
    print()

# 
# # 
# # # 
# # # # 


In [35]:

for i in range(1,5):
    print("# "*i)

# 
# # 
# # # 
# # # # 


In [36]:

for i in range(1,5):
    for j in range(4):
        if i>j:
            print('#', end = " ")
    print()

# 
# # 
# # # 
# # # # 


In [37]:

for i in range(4):
    for j in range(4-i):
        print('#', end = " ")
    print()


# # # # 
# # # 
# # 
# 


# For Else

In [38]:

nums = [12,15,18,21,26]
for num in nums:
    if num % 5 == 0:
        print(num)

15


In [39]:
nums = [12,15,18,21,26,20,30]

for num in nums:
    if num % 5 == 0:
        print(num)

15
20
30


In [40]:
nums = [12,14,18,21,20,25]

for num in nums:
    if num % 5 == 0:
        print(num)  
        break

20


In [41]:

nums = [10,14,18,21,5,10]

for num in nums:
    if num % 5 == 0:
        print(num)  
        break #it will print only 1 number then it break  

10


In [42]:

nums = [12,13,14,16,17,18]

for num in nums:
    if num % 5==0:
        print(num)
        break
else:
    print('number not found')

number not found


In [43]:
nums = [12,13,15,14,16,17,18,25,30]

for num in nums:
    if num % 5==0:
        print(num)
        break
else:
    print('number not found')

15



# Prime Number

In [44]:

num = 13

for i in range(2,num):
    if num % i == 0:
        print('Not prime number')
        break
else:
    print("prime number")

prime number


In [45]:

num = 14

for i in range(2,num):
    if num % i == 0:
        print('Not prime number')
        break
else:
    print("prime number")

Not prime number



# ARRAY in Python

In [48]:
import numpy as np

In [49]:

np.__version__

'2.3.5'

In [50]:

l = [1,2,3,4,5,6,7,8]
l


[1, 2, 3, 4, 5, 6, 7, 8]

In [51]:

type(l)


list

In [52]:

arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [53]:

type(arr)

numpy.ndarray

In [54]:

print(type(l))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [55]:

np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [56]:

np.arange(5,10)


array([5, 6, 7, 8, 9])

In [57]:

np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [58]:

np.arange(20,10) # 1st value has to be small

array([], dtype=int64)

In [59]:

np.arange(20,10) # 1st value has to be small

array([], dtype=int64)

In [60]:

np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])