In [1]:
import numpy as np

In [2]:

# creat list
my_list = [0,1,2,3,4,5]
my_list


[0, 1, 2, 3, 4, 5]

In [3]:

type(my_list)

list

In [4]:

np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:

np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [6]:

np.zeros(5)#paramiter tunning

array([0., 0., 0., 0., 0.])

In [7]:

np.zeros(5,dtype = int)# Hyper paramiter tunning

array([0, 0, 0, 0, 0])

In [8]:

np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [9]:
np.zeros((2,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:

np.zeros((10,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:

np.ones(5)


array([1., 1., 1., 1., 1.])

In [12]:

np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:

np.two((2,3), dtype=int)

AttributeError: module 'numpy' has no attribute 'two'

In [14]:

np.three(4)

AttributeError: module 'numpy' has no attribute 'three'

In [15]:

rand(2,3)

NameError: name 'rand' is not defined

In [16]:

random.rand(2,3)

NameError: name 'random' is not defined

In [17]:

np.random.rand(2)# it will generate only floate value

array([0.32791385, 0.15104402])

In [18]:

np.random.rand(2,3)

array([[0.91932184, 0.28353834, 0.71826236],
       [0.35454394, 0.11508951, 0.77767239]])

In [19]:

np.random.randint(2)# it always 2 value 1, and 0

0

In [20]:

np.random.randint(2,9)

7

In [21]:

#generate random integer between 2 - 9 where 9 is exclude, 
np.random.randint(2,9,4)# give me 4 random integer

array([6, 7, 6, 5], dtype=int32)

In [22]:

np.random.randint(10,40,(10,10))

array([[10, 21, 17, 33, 31, 14, 27, 29, 25, 10],
       [13, 18, 26, 25, 38, 17, 28, 17, 17, 15],
       [29, 29, 20, 36, 19, 13, 39, 18, 33, 28],
       [35, 39, 14, 18, 35, 13, 18, 22, 18, 35],
       [16, 35, 35, 39, 14, 32, 33, 27, 30, 37],
       [36, 36, 37, 28, 18, 32, 26, 23, 27, 18],
       [31, 38, 37, 34, 11, 32, 35, 38, 10, 11],
       [27, 27, 38, 17, 28, 11, 26, 39, 16, 19],
       [36, 36, 20, 20, 29, 10, 12, 19, 18, 20],
       [34, 28, 19, 23, 10, 19, 13, 16, 20, 25]], dtype=int32)

In [23]:

np.random.rand(5)

array([0.35566694, 0.2156843 , 0.30780412, 0.15150817, 0.52086459])

In [24]:

np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [25]:

np.random.rand(3,5)

array([[0.24832837, 0.83460126, 0.20475725, 0.08075379, 0.94838237],
       [0.13712529, 0.90920372, 0.46899061, 0.06774342, 0.6212867 ],
       [0.14070923, 0.1328642 , 0.99518134, 0.45392512, 0.51795126]])

In [26]:

np.random.randint(4,6)

4

In [27]:

np.random.randint(2,20,4)

array([12, 12, 11, 17], dtype=int32)

In [28]:

np.random.randint(0,1) 

0

In [29]:

np.random.randint(10,20,5)

array([13, 10, 16, 19, 16], dtype=int32)

In [30]:

np.arange(1,13)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
np.arange(1,13).reshape(3,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:

np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:

np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [34]:
import numpy as np

def generate_otp(length=4):
    # Generate OTP of given length using np.random.randint
    otp = ''.join([str(np.random.randint(0, 10)) for _ in range(length)])
    return otp

# Example usage
print("Your OTP is:", generate_otp())

Your OTP is: 0326


In [35]:

arr1 = np.random.randint(10,40,(10,10))
print(arr1)


[[10 23 17 13 26 17 14 35 34 37]
 [17 27 18 35 17 22 15 22 36 28]
 [13 17 25 12 30 36 22 35 17 20]
 [28 15 13 34 19 26 33 13 38 12]
 [38 18 32 28 28 39 24 21 26 13]
 [31 35 29 16 17 31 13 14 18 29]
 [24 31 16 33 35 11 11 35 25 13]
 [32 21 14 27 31 31 21 38 15 21]
 [31 15 10 26 38 10 36 11 18 39]
 [39 35 14 38 13 35 24 20 16 22]]


In [36]:

arr1

array([[10, 23, 17, 13, 26, 17, 14, 35, 34, 37],
       [17, 27, 18, 35, 17, 22, 15, 22, 36, 28],
       [13, 17, 25, 12, 30, 36, 22, 35, 17, 20],
       [28, 15, 13, 34, 19, 26, 33, 13, 38, 12],
       [38, 18, 32, 28, 28, 39, 24, 21, 26, 13],
       [31, 35, 29, 16, 17, 31, 13, 14, 18, 29],
       [24, 31, 16, 33, 35, 11, 11, 35, 25, 13],
       [32, 21, 14, 27, 31, 31, 21, 38, 15, 21],
       [31, 15, 10, 26, 38, 10, 36, 11, 18, 39],
       [39, 35, 14, 38, 13, 35, 24, 20, 16, 22]], dtype=int32)

In [37]:

print(arr1)


[[10 23 17 13 26 17 14 35 34 37]
 [17 27 18 35 17 22 15 22 36 28]
 [13 17 25 12 30 36 22 35 17 20]
 [28 15 13 34 19 26 33 13 38 12]
 [38 18 32 28 28 39 24 21 26 13]
 [31 35 29 16 17 31 13 14 18 29]
 [24 31 16 33 35 11 11 35 25 13]
 [32 21 14 27 31 31 21 38 15 21]
 [31 15 10 26 38 10 36 11 18 39]
 [39 35 14 38 13 35 24 20 16 22]]


In [38]:

arr1[5]

array([31, 35, 29, 16, 17, 31, 13, 14, 18, 29], dtype=int32)

In [39]:

arr2 = np.random.randint(2, 9,(5,7)) 
print(arr2)

[[5 8 5 6 3 6 3]
 [5 8 8 6 8 4 4]
 [7 4 4 5 4 6 8]
 [6 6 7 7 3 2 7]
 [6 7 7 6 8 4 6]]


In [40]:

arr2[-4]

array([5, 8, 8, 6, 8, 4, 4], dtype=int32)

In [41]:

arr2

array([[5, 8, 5, 6, 3, 6, 3],
       [5, 8, 8, 6, 8, 4, 4],
       [7, 4, 4, 5, 4, 6, 8],
       [6, 6, 7, 7, 3, 2, 7],
       [6, 7, 7, 6, 8, 4, 6]], dtype=int32)

In [42]:

arr2[2:10] 

array([[7, 4, 4, 5, 4, 6, 8],
       [6, 6, 7, 7, 3, 2, 7],
       [6, 7, 7, 6, 8, 4, 6]], dtype=int32)

In [43]:

arr2

array([[5, 8, 5, 6, 3, 6, 3],
       [5, 8, 8, 6, 8, 4, 4],
       [7, 4, 4, 5, 4, 6, 8],
       [6, 6, 7, 7, 3, 2, 7],
       [6, 7, 7, 6, 8, 4, 6]], dtype=int32)

In [44]:

arr2[:]

array([[5, 8, 5, 6, 3, 6, 3],
       [5, 8, 8, 6, 8, 4, 4],
       [7, 4, 4, 5, 4, 6, 8],
       [6, 6, 7, 7, 3, 2, 7],
       [6, 7, 7, 6, 8, 4, 6]], dtype=int32)

In [45]:

arr2[::-1]

array([[6, 7, 7, 6, 8, 4, 6],
       [6, 6, 7, 7, 3, 2, 7],
       [7, 4, 4, 5, 4, 6, 8],
       [5, 8, 8, 6, 8, 4, 4],
       [5, 8, 5, 6, 3, 6, 3]], dtype=int32)

In [46]:

arr2

array([[5, 8, 5, 6, 3, 6, 3],
       [5, 8, 8, 6, 8, 4, 4],
       [7, 4, 4, 5, 4, 6, 8],
       [6, 6, 7, 7, 3, 2, 7],
       [6, 7, 7, 6, 8, 4, 6]], dtype=int32)

In [47]:

arr2[::3]

array([[5, 8, 5, 6, 3, 6, 3],
       [6, 6, 7, 7, 3, 2, 7]], dtype=int32)

In [48]:

arr2

array([[5, 8, 5, 6, 3, 6, 3],
       [5, 8, 8, 6, 8, 4, 4],
       [7, 4, 4, 5, 4, 6, 8],
       [6, 6, 7, 7, 3, 2, 7],
       [6, 7, 7, 6, 8, 4, 6]], dtype=int32)

In [49]:

arr2[3,4] 

np.int32(3)

In [50]:

print(arr2[3,4])

3


In [55]:

arr2

array([[ 5, 10,  5,  6,  3,  6,  3],
       [ 5,  8,  8,  6,  8,  4,  4],
       [ 7,  4,  4,  5,  4,  6,  8],
       [ 6,  6,  7,  7,  3,  2,  7],
       [ 6,  7,  7,  6,  8,  4,  6]], dtype=int32)

In [56]:

print(arr2[-4, -5]) 

8


In [57]:

arr2[0, 1] = 10

In [58]:

arr2

array([[ 5, 10,  5,  6,  3,  6,  3],
       [ 5,  8,  8,  6,  8,  4,  4],
       [ 7,  4,  4,  5,  4,  6,  8],
       [ 6,  6,  7,  7,  3,  2,  7],
       [ 6,  7,  7,  6,  8,  4,  6]], dtype=int32)

In [59]:

arr2[:, 0]

array([5, 5, 7, 6, 6], dtype=int32)

In [60]:

arr2[:, -3]

array([3, 8, 4, 3, 8], dtype=int32)

In [61]:

arr2

array([[ 5, 10,  5,  6,  3,  6,  3],
       [ 5,  8,  8,  6,  8,  4,  4],
       [ 7,  4,  4,  5,  4,  6,  8],
       [ 6,  6,  7,  7,  3,  2,  7],
       [ 6,  7,  7,  6,  8,  4,  6]], dtype=int32)

In [62]:

arr2[2:5, 2:5] 

array([[4, 5, 4],
       [7, 7, 3],
       [7, 6, 8]], dtype=int32)

In [63]:

arr2

array([[ 5, 10,  5,  6,  3,  6,  3],
       [ 5,  8,  8,  6,  8,  4,  4],
       [ 7,  4,  4,  5,  4,  6,  8],
       [ 6,  6,  7,  7,  3,  2,  7],
       [ 6,  7,  7,  6,  8,  4,  6]], dtype=int32)

In [64]:

arr2[1:4, 2:4]

array([[8, 6],
       [4, 5],
       [7, 7]], dtype=int32)

In [65]:
arr2

array([[ 5, 10,  5,  6,  3,  6,  3],
       [ 5,  8,  8,  6,  8,  4,  4],
       [ 7,  4,  4,  5,  4,  6,  8],
       [ 6,  6,  7,  7,  3,  2,  7],
       [ 6,  7,  7,  6,  8,  4,  6]], dtype=int32)

In [66]:

arr2 > 5 

array([[False,  True, False,  True, False,  True, False],
       [False,  True,  True,  True,  True, False, False],
       [ True, False, False, False, False,  True,  True],
       [ True,  True,  True,  True, False, False,  True],
       [ True,  True,  True,  True,  True, False,  True]])

In [67]:
arr2[arr2 > 5] 

array([10,  6,  6,  8,  8,  6,  8,  7,  6,  8,  6,  6,  7,  7,  7,  6,  7,
        7,  6,  8,  6], dtype=int32)

In [68]:

arr2[arr2 >= 5]

array([ 5, 10,  5,  6,  6,  5,  8,  8,  6,  8,  7,  5,  6,  8,  6,  6,  7,
        7,  7,  6,  7,  7,  6,  8,  6], dtype=int32)

In [69]:

arr2[arr2 != 5]

array([10,  6,  3,  6,  3,  8,  8,  6,  8,  4,  4,  7,  4,  4,  4,  6,  8,
        6,  6,  7,  7,  3,  2,  7,  6,  7,  7,  6,  8,  4,  6],
      dtype=int32)

In [70]:

arr2[arr2 == 5]

array([5, 5, 5, 5], dtype=int32)

In [72]:

import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr)


[0 1 2 3 4 5]


In [73]:

arr

array([0, 1, 2, 3, 4, 5])

In [74]:

arr.reshape(3,2) 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [75]:

arr.reshape(6,1) 

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [76]:

arr.reshape(2,4) 

ValueError: cannot reshape array of size 6 into shape (2,4)

In [77]:
arr.reshape(3,2,order='C') 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [78]:

arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [79]:

arr.reshape(2,3,order='F')


array([[0, 2, 4],
       [1, 3, 5]])

In [80]:

arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [81]:

arr.reshape(4,3)

ValueError: cannot reshape array of size 6 into shape (4,3)

In [82]:
arr.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [83]:

# importing Numpy package 
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order 

print("\n  C type array:")
for num_array in np.nditer(num_array, order="C"):
	print(num_array,end=' ')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]

  C type array:
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

In [84]:

mat = np.arange(0,100).reshape(10,10) 

In [85]:

mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [86]:
mat = np.arange(0,100).reshape(10,10)

In [88]:

mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [89]:

arr

array([0, 1, 2, 3, 4, 5])

In [90]:

arr.max()

np.int64(5)

In [91]:

arr.min()

np.int64(0)