In [1]:
import numpy as np


In [2]:
my_list = [0,1,2,3,4,5]


In [3]:
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(20,10)

array([], dtype=int64)

In [10]:
np.arange(20,10,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [11]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [12]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [15]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [16]:
np.zeros((2,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [17]:
np.zeros((10,10 ),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
np.ones((3,2), dtype= int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [21]:
np.full((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])

In [22]:
np.full((3,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [23]:
random.rand(3)

NameError: name 'random' is not defined

In [ ]:
np.random.rand(2)

In [24]:
np.random.rand(2,3)

array([[0.15646803, 0.72509728, 0.83237653],
       [0.78060223, 0.46210948, 0.68227296]])

In [25]:
np.random.randint(2)

0

In [26]:
np.random.randint(2,9)

8

In [27]:
np.random.randint(2,9,4)

array([3, 8, 3, 4], dtype=int32)

In [28]:
import numpy as np

def generate_otp(length=4):
    otp = ''.join([str(np.random.randint(0, 10)) for _ in range(length)])
    return otp

print("Your OTP is:", generate_otp())

Your OTP is: 7544


In [29]:
import numpy as np

def Generate_otp(length = 4):

    otp = ''.join([str(np.random.randint(0,10)) for _ in range(length)])
    return otp

print("Your OTP is",Generate_otp())

Your OTP is 9482


In [31]:
import random

def guessing_game():
    number = random.randint(1, 10)

    print("I selected a number between 1 and 10.")

    guess = int(input("Enter your guess: "))

    if guess == number:
        print("🎉 Correct!")
    else:
        print("❌ Wrong!")
        print("The number was:", number)

guessing_game()

I selected a number between 1 and 10.


Enter your guess:  4


❌ Wrong!
The number was: 10


In [ ]:
import random

def guess_number():

    number = random.randint(0,10)

    print("select number")

    guess = int(input("enter input"))

    if guess==number:
        print("Your correct")

    else:
        print("Your Worng")

guess_number()

select number


In [13]:
np.random.randint(10,40,(10,10))

array([[37, 10, 13, 26, 36, 37, 26, 39, 31, 34],
       [13, 29, 33, 10, 26, 21, 22, 29, 31, 30],
       [37, 10, 23, 13, 13, 22, 34, 30, 27, 28],
       [26, 33, 12, 18, 35, 24, 29, 30, 14, 13],
       [37, 21, 17, 24, 19, 14, 33, 35, 30, 38],
       [30, 29, 18, 31, 12, 21, 18, 16, 31, 20],
       [20, 37, 21, 36, 19, 10, 18, 34, 14, 13],
       [39, 27, 15, 18, 17, 34, 31, 16, 12, 23],
       [15, 10, 28, 32, 22, 24, 10, 26, 21, 23],
       [37, 19, 38, 38, 14, 22, 21, 17, 31, 10]], dtype=int32)

In [14]:
arr = np.random.randint(10,40,(10,10))
print(arr)

[[20 27 13 39 21 17 27 25 19 21]
 [18 20 22 37 14 24 21 37 17 39]
 [31 10 36 27 33 21 25 14 22 38]
 [17 13 12 29 25 14 22 12 15 32]
 [18 35 32 14 25 14 33 30 14 13]
 [12 35 10 16 34 10 35 11 21 10]
 [11 23 26 32 39 25 15 14 25 20]
 [14 13 26 37 11 27 29 10 16 10]
 [25 16 34 12 32 25 11 30 21 31]
 [30 27 29 35 29 17 33 36 20 34]]


In [15]:
arr[5]

array([12, 35, 10, 16, 34, 10, 35, 11, 21, 10], dtype=int32)

In [16]:
arr1 = np.random.randint(2,9,(5,7))

arr1

array([[3, 8, 6, 3, 2, 6, 5],
       [2, 8, 2, 3, 2, 6, 3],
       [2, 3, 2, 5, 6, 8, 3],
       [4, 7, 4, 2, 2, 3, 8],
       [4, 3, 7, 7, 4, 6, 7]], dtype=int32)

In [17]:
arr1[-3]

array([2, 3, 2, 5, 6, 8, 3], dtype=int32)

In [18]:
arr1

array([[3, 8, 6, 3, 2, 6, 5],
       [2, 8, 2, 3, 2, 6, 3],
       [2, 3, 2, 5, 6, 8, 3],
       [4, 7, 4, 2, 2, 3, 8],
       [4, 3, 7, 7, 4, 6, 7]], dtype=int32)

In [19]:
arr1[2:10]

array([[2, 3, 2, 5, 6, 8, 3],
       [4, 7, 4, 2, 2, 3, 8],
       [4, 3, 7, 7, 4, 6, 7]], dtype=int32)

In [20]:
arr1[2:7]

array([[2, 3, 2, 5, 6, 8, 3],
       [4, 7, 4, 2, 2, 3, 8],
       [4, 3, 7, 7, 4, 6, 7]], dtype=int32)

In [21]:
arr1[:]

array([[3, 8, 6, 3, 2, 6, 5],
       [2, 8, 2, 3, 2, 6, 3],
       [2, 3, 2, 5, 6, 8, 3],
       [4, 7, 4, 2, 2, 3, 8],
       [4, 3, 7, 7, 4, 6, 7]], dtype=int32)

In [22]:
arr1[::-1]

array([[4, 3, 7, 7, 4, 6, 7],
       [4, 7, 4, 2, 2, 3, 8],
       [2, 3, 2, 5, 6, 8, 3],
       [2, 8, 2, 3, 2, 6, 3],
       [3, 8, 6, 3, 2, 6, 5]], dtype=int32)

In [23]:
arr1[2,3]

np.int32(5)

In [24]:
arr1[2,4]

np.int32(6)

In [25]:
arr1[3,4]

np.int32(2)

In [26]:
arr1[-4,-5]

np.int32(2)

In [27]:
arr1[-5,-5]

np.int32(6)

In [28]:
arr1[-3,-5]

np.int32(2)

In [29]:
arr1[2,4] = 10

In [30]:
arr1

array([[ 3,  8,  6,  3,  2,  6,  5],
       [ 2,  8,  2,  3,  2,  6,  3],
       [ 2,  3,  2,  5, 10,  8,  3],
       [ 4,  7,  4,  2,  2,  3,  8],
       [ 4,  3,  7,  7,  4,  6,  7]], dtype=int32)

In [31]:
arr[:,0]

array([20, 18, 31, 17, 18, 12, 11, 14, 25, 30], dtype=int32)

In [32]:
arr1[2:5,2:5]

array([[ 2,  5, 10],
       [ 4,  2,  2],
       [ 7,  7,  4]], dtype=int32)

In [33]:
arr1

array([[ 3,  8,  6,  3,  2,  6,  5],
       [ 2,  8,  2,  3,  2,  6,  3],
       [ 2,  3,  2,  5, 10,  8,  3],
       [ 4,  7,  4,  2,  2,  3,  8],
       [ 4,  3,  7,  7,  4,  6,  7]], dtype=int32)

# Masking Filtering

In [34]:
arr1>5

array([[False,  True,  True, False, False,  True, False],
       [False,  True, False, False, False,  True, False],
       [False, False, False, False,  True,  True, False],
       [False,  True, False, False, False, False,  True],
       [False, False,  True,  True, False,  True,  True]])

In [35]:
arr1[arr1>5]

array([ 8,  6,  6,  8,  6, 10,  8,  7,  8,  7,  7,  6,  7], dtype=int32)

In [36]:
arr1[arr1>=5]

array([ 8,  6,  6,  5,  8,  6,  5, 10,  8,  7,  8,  7,  7,  6,  7],
      dtype=int32)

In [37]:
arr1[arr1==5]

array([5, 5], dtype=int32)

In [38]:
arr1[arr1 != 5] 

array([ 3,  8,  6,  3,  2,  6,  2,  8,  2,  3,  2,  6,  3,  2,  3,  2, 10,
        8,  3,  4,  7,  4,  2,  2,  3,  8,  4,  3,  7,  7,  4,  6,  7],
      dtype=int32)

# Reshape

In [39]:
arr = np.array([0,1,2,3,4,5])

In [40]:
arr

array([0, 1, 2, 3, 4, 5])

# wrong reshape

In [42]:
arr.reshape(4,3)

ValueError: cannot reshape array of size 6 into shape (4,3)

In [41]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

# Maximum and minimum

In [44]:
arr.max()

np.int64(5)

In [51]:
arr = np.array( [0,1,2,3,4,5])

In [52]:
arr

array([0, 1, 2, 3, 4, 5])

In [53]:
arr.min()

np.int64(0)