In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.arange(0,10,3)
print(b)

[0 3 6 9]


# Zeros

In [13]:
d = np.zeros((2,5)) 
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
d = np.zeros((2,3), dtype = int)
print(d)

[[0 0 0]
 [0 0 0]]


# Ones

In [17]:
e = np.ones((2,3))
print(e)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
e = np.ones((2,3), dtype = int)
print(e)

[[1 1 1]
 [1 1 1]]


# eye 

### its create diagonal = 1 , other value =0

In [19]:
f = np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Manipulation

# Reshape()

In [20]:
a1 = np.array([1,2,3])
print(a1)

[1 2 3]


In [21]:
re = np.reshape(a1,(1,3))
print(re)

[[1 2 3]]


In [22]:
re = np.reshape(a1,(3,1))
print(re)

[[1]
 [2]
 [3]]


# ravel() --Flatten

In [26]:
f1 = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10]
])

print(f1)     # this 2d array

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [27]:
flattened = np.ravel(f1)
print(flattened)            # simple mining 2d to 1d

[ 1  2  3  4  5  6  7  8  9 10]


# transpose()

In [28]:
e1 = np.array([
    [1,2],
    [3,4]
])
print(e1)

[[1 2]
 [3 4]]


In [29]:
tr = np.transpose(e1)
print(tr)

[[1 3]
 [2 4]]


In [30]:
# Rows becomes columns

# vstack()

### vstack = vertical stack
##### one row below another

In [32]:
a2 = np.array([1,2])
a3 = np.array([3,4])

np.vstack([a2,a3])

array([[1, 2],
       [3, 4]])

# hstack

### hstack = Horizontal stack

### One array beside another.

In [33]:
np.hstack([a2,a3])

array([1, 2, 3, 4])

# hstack = Horizontal stack

# One array beside another.

# 3. Mathematical Functions

In [34]:
g = np.array ([1,2,3,4])

### np.add

In [35]:
np.add(g,2)    #It adds 2 to every element.

array([3, 4, 5, 6])

# np.power()

In [36]:
np.power(g,2)       

# 1² = 1
# 2² = 4
# 3² = 9
# 4² = 16

array([ 1,  4,  9, 16])

# np.sqrt()

In [37]:
np.sqrt(g)   #Square root of every element.

array([1.        , 1.41421356, 1.73205081, 2.        ])

# np.dot()

In [39]:
a = np.array([1, 2, 3])
g = np.array([1, 2, 3, 4])

np.dot(a, g)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [40]:
# ⚠️ This will give an error, because:

# a → 3 elements
# g → 4 elements

#For dot product, these 1D arrays need matching sizes

In [42]:
a = np.array([1,2,3])
g = np.array([4,5,6])

dot = np.dot(a,g)
print(dot)                 #Calculation:

                           #1×4 + 2×5 + 3×6
                           #= 4 + 10 + 18
                           #= 32

32


# 4.statistical function

In [43]:
s = np.array([1,2,3,4])

# mean()

In [45]:
np.mean(s)

np.float64(2.5)

# Calculation:

# (1 + 2 + 3 + 4) / 4
# = 2.5

# var()
# variance.

In [47]:
np.var(s) #This calculates variance.

np.float64(1.25)

# std()
# standard deviation

In [48]:
np.std(s)

np.float64(1.118033988749895)

# min()

In [49]:
np.min(s)  #Smallest value.

np.int64(1)

# max()

In [50]:
np.max(s)  #Largest value.

np.int64(4)

### Easy memory:
### mean → average
### var  → variance
### std  → standard deviation
### min  → smallest
### max  → largest

# 5. Linear Algebra

In [51]:
matrix = np.array([
    [1, 2],
    [3, 4]
])

In [53]:
np.transpose(matrix)


array([[1, 3],
       [2, 4]])

In [54]:
np.linalg.det(matrix)


np.float64(-2.0000000000000004)

In [55]:
np.linalg.inv(matrix)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Easy way to remember 🧠
### Code	Meaning
### np.transpose()	Rows ↔ Columns
### np.linalg.det()	Find determinant
### np.linalg.inv()	Find inverse

# 6. Random Functions

### np.random.rand()

In [57]:
random_vals = np.random.rand(3) 
print(random_vals)

[0.87685421 0.6098028  0.85112103]


# np.random.seed()

In [59]:
np.random.seed(0)

In [61]:
np.random.seed(0)
print(np.random.rand(3))       #Easy meaning:

                               #seed = fixed starting point for random numbers.

[0.5488135  0.71518937 0.60276338]


# np.random.randint()

In [64]:
np.random.randint(0,10 ,size=5)

#np.random.randint(start, stop, size)

array([2, 4, 7, 6, 8], dtype=int32)

In [66]:
np.random.randint(0, 10)

1

# 7. Boolean & Logical Functions

#### Boolean means:

##### True
##### False

In [67]:
logical_test = np.array([True, False, True])

# np.all()

In [68]:
np.all(logical_test)  #Are ALL values True?

np.False_

In [69]:
#Example
x = np.array([True, True, True])
np.all(x)
#all() → everything must be True.

np.True_

# np.any()

In [70]:
x = np.array([False, False, True])

np.any(x)
# Because at least one value is True.

np.True_

### Easy memory:

##### all → ALL must be True
##### any → ANY one can be True

# 8. Set Operations

In [71]:
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])

### intersection

In [72]:
np.intersect1d(set_a,set_b

#Intersection means:

#Common values.

#Both arrays contain:

array([3, 4])

# Union

In [73]:
np.union1d(set_a, set_b)

# Union means:

# Combine all unique values.

array([1, 2, 3, 4, 5, 6])

# 9. Array Attributes

In [74]:
a = np.array([1,2,3])


# shape

In [75]:
a.shape      #Tells the structure/size of dimensions.

(3,)

In [78]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

#2 rows × 3 columns

In [77]:
a.shape 

(2, 3)

# size()

In [80]:
a.size   #Number of elements.

6

# ndim()

In [81]:
a.ndim

2

# dtype()

In [82]:
a.dtype

dtype('int64')

#### ⭐ Remember these 4
#### shape → structure
#### size  → total elements
#### ndim  → number of dimensions
#### dtype → data type

# 10. Other Functions

##### np.copy()

In [84]:
a = np.array([1, 2, 3])

copied_array = np.copy(a)
print(copied_array)

[1 2 3]


##### nbytes()

In [85]:
a.nbytes

24

##### shares_memory()

In [86]:
np.shares_memory(a, copied_array)

#Checks whether two arrays share the same memory.

#Because np.copy() creates a separate copy

False

# 🧠 FINAL NUMPY CHEAT SHEET

In [ ]:
| Function              | Simple meaning        |
| --------------------- | --------------------- |
| `np.array()`          | Create array          |
| `np.arange()`         | Create sequence       |
| `np.zeros()`          | Create zeros          |
| `np.ones()`           | Create ones           |
| `np.eye()`            | Identity matrix       |
| `np.reshape()`        | Change shape          |
| `np.ravel()`          | Flatten               |
| `np.transpose()`      | Rows ↔ columns        |
| `np.vstack()`         | Stack vertically      |
| `np.hstack()`         | Stack horizontally    |
| `np.add()`            | Add                   |
| `np.power()`          | Power/square          |
| `np.sqrt()`           | Square root           |
| `np.dot()`            | Dot product           |
| `np.mean()`           | Average               |
| `np.var()`            | Variance              |
| `np.std()`            | Standard deviation    |
| `np.min()`            | Minimum               |
| `np.max()`            | Maximum               |
| `np.random.rand()`    | Random decimals       |
| `np.random.seed()`    | Repeat random results |
| `np.random.randint()` | Random integers       |
| `np.all()`            | All True?             |
| `np.any()`            | Any True?             |
| `np.intersect1d()`    | Common values         |
| `np.union1d()`        | Combine unique values |
| `.shape`              | Shape                 |
| `.size`               | Number of elements    |
| `.ndim`               | Dimensions            |
| `.dtype`              | Data type             |
| `np.copy()`           | Copy array            |
| `.nbytes`             | Memory in bytes       |
| `np.shares_memory()`  | Check shared memory   | 
